- hosts: pfservers
  name: Set venom vars
  become: True
  gather_facts: True
  gather_subset: ['!all']

  tasks:
  # packetfence-test or {{ venom_dir }}/vars/local.yml should exist
  - import_tasks: tasks/install_venom_local_vars.yml
