name: Cli RADIUS Config Teardown
testcases:
- name: delete_radius_source
  steps:
  - type: pf_api_source_delete
    id: "{{.cli_login_radius.sources.id}}"

- name: Default_Switch_192.168.0.1_back_to_default
  steps:
  - type: pf_api_switch_patch
    id: '{{.cli_login_radius.switch.ip}}'
    body: >-
      {
        "cliAccess": null
      }

- name: delete_radius_realm
  steps:
  - type: pf_api_realm_delete
    id: "{{.cli_login_radius.realm.id}}"
